# Generated by Django 2.2.6 on 2019-10-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='flor')),
                ('descripcion', models.TextField(max_length=300)),
                ('valor', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
